# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CityName', models.CharField(max_length=60)),
                ('ActualMaxConn', models.IntegerField()),
                ('numDialPeer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cubes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CubeName', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField()),
                ('usr', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=50)),
                ('numTrunks', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='cubes',
            name='idMaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxConnections.Master'),
        ),
        migrations.AddField(
            model_name='city',
            name='idMaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxConnections.Master'),
        ),
    ]
