# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 01:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maxConnections', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='numDialPeer',
            new_name='DialPeer',
        ),
    ]
